import defaultTheme from 'tailwindcss/defaultTheme'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './resources/views/**/*.blade.php',
    './resources/js/**/*.js',
    './app/**/*.php',
    './storage/framework/views/*.php',
    './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
  ],
  theme: {
    extend: {
      colors: {
        // GOV.UK Design System — https://design-system.service.gov.uk/styles/colour
        'govuk-blue': '#1d70b8',
        'govuk-dark-blue': '#003078',
        'govuk-light-blue': '#5694ca',
        'govuk-yellow': '#ffdd00',
        'govuk-black': '#0b0c0c',
        'govuk-dark-grey': '#505a5f',
        'govuk-mid-grey': '#b1b4b6',
        'govuk-light-grey': '#f3f2f1',
        'govuk-green': '#00703c',
        'govuk-red': '#d4351c',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b0c0c',
        'on-surface-variant': '#505a5f',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#b1b4b6',
        'outline-variant': '#b1b4b6',
        'surface-tint': '#1d70b8',
        primary: '#1d70b8',
        'on-primary': '#ffffff',
        'primary-container': '#1d70b8',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#5694ca',
        secondary: '#505a5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#f3f2f1',
        'on-secondary-container': '#0b0c0c',
        tertiary: '#00703c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00703c',
        'on-tertiary-container': '#ffffff',
        error: '#d4351c',
        'on-error': '#ffffff',
        'error-container': '#d4351c',
        'on-error-container': '#ffffff',
        'primary-fixed': '#dbeaff',
        'primary-fixed-dim': '#5694ca',
        'on-primary-fixed': '#0b0c0c',
        'on-primary-fixed-variant': '#003078',
        'secondary-fixed': '#f3f2f1',
        'secondary-fixed-dim': '#b1b4b6',
        'on-secondary-fixed': '#0b0c0c',
        'on-secondary-fixed-variant': '#505a5f',
        'tertiary-fixed': '#cce2d8',
        'tertiary-fixed-dim': '#00703c',
        'on-tertiary-fixed': '#0b0c0c',
        'on-tertiary-fixed-variant': '#00703c',
        background: '#ffffff',
        'on-background': '#0b0c0c',
        'surface-variant': '#f3f2f1',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1rem',
        margin: '1.5rem',
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
      },
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-lg': ['Inter'],
        'label-md': ['Inter'],
        'label-mono': ['JetBrains Mono'],
        'headline-xl': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'metric-val': ['Inter'],
      },
      fontSize: {
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-xl': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['15px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'metric-val': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
